version: "3.8"
services:
  app:
    build:
      context: .
    environment:
      - JDBC_CONNECTION_URL=jdbc:mysql://mysql:3306/databaselumi
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=usernamelumi
      - MYSQL_PASSWORD=passwordlumi
      - MYSQL_ROOT_PASSWORD=passwordlumi
      - MYSQL_DATABASE=databaselumi